# Generated by Django 5.2.4 on 2025-07-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='post_id',
            new_name='post',
        ),
    ]
